package io.dataspin.analyticsSDK;

/**
 * Created by rafal on 14.03.15.
 */
public enum ErrorType {
    UNKNOWN_ERROR,
    JSON_PROCESSING_ERROR,
    REQUEST_CREATION_ERROR,
    CONNECTION_ERROR,
    API_KEY_NOT_PROVIDED,
    CORRESPONDING_URL_MISSING,
    USER_NOT_REGISTERED,
    DEVICE_NOT_REGISTERED,
    INTERNET_NOTREACHABLE,
    SESSION_NOT_STARTED,
    BACKLOG_CORRUPTED,
    INTERNAL_PLUGIN_ERROR,
    BACKLOG_FLUSH_ERROR,
    QUANTITY_ERROR;
}
